image: dockershelf/latex:full

before_script:
    - apt-get install -qy python3-pygments

build:
    script:
    - cd spec
    - lualatex -shell-escape -recorder '\def\nocomments{}\input{doc.tex}'
    - bibtex  "doc"
    - lualatex -shell-escape -recorder '\def\nocomments{}\input{doc.tex}'
    - bibtex  "doc"
    - lualatex -shell-escape -recorder '\def\nocomments{}\input{doc.tex}'
    - cd ..
    - cp spec/doc.pdf specification.pdf
    artifacts:
        paths:
        - specification.pdf

