name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: xu-cheng/texlive-action@v3
      with:
        run: |
          cd spec
          latexmk -interaction=nonstopmode -pdf -shell-escape -lualatex doc
    - uses: actions/upload-artifact@v7
      with:
        path: spec/doc.pdf
    - name: Rebuild Webpage
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: 87249859
        repo: alethe-proofs/alethe-proofs.github.io
        token: '${{ secrets.ALETHE_SPEC_TOKEN }}'
